kind: pipeline
type: docker
name: direct-execution

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: execute-command
    image: alpine
    debug: true
    commands:
      - echo "Executing command directly on the server."
      - # Add any other shell commands you need to run here
      - ls -l
