kind: pipeline
type: docker
name: simple-test-log

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: display-test-log
    image: alpine
    commands:
      - echo "Test log The pipeline is running successfully."
