kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: update-production
    image: appleboy/drone-ssh
    settings:
      host: 188.166.85.184
      username: root
      key:
        from_secret: private_vm_ssh
      debug: true
      port: 22
      script:
        - echo "Deploying to production server"
        - cd /home/ouadie/Game-backend
        - git pull