kind: pipeline
type: docker
name: default

trigger:
  branch:
  - main
  event:
    include:
      - push
      - custom

steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: 161.35.247.162
      port: 22
      username: root
      key:
        from_secret: private_key
      script:
        - echo 'drone working'
        - cd /home/ouadie/Game-backend
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_github
        - git pull
        - npm install
        - echo 'drone commands executed'
