kind: pipeline
type: docker
name: log-test

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: log-message
    image: alpine
    commands:
      - echo "This 1 is a test log message from the Drone CI pipeline."
