kind: pipeline
type: docker
name: default


# trigger:
#   event:
#     - push
#     - custom
trigger:
  branch:
  - main
  event:
    include:
      - push
      # - custom



steps:
  - name: log-message
    image: alpine
    commands:
      - echo "This is a test log message from the Drone CI pipeline."

# trigger:
#   event:
#     - push

# steps:
# - name: build
#   image: docker:latest
#   commands:
#     - echo "Building the Docker image..."