kind: pipeline
type: docker
name: default


# trigger:
#   event:
#     - push
#     - custom
trigger:
  branch:
  - main
  event:
    include:
      - push
      - custom



steps:
  - name: log-message
    image: alpine
    commands:
      - echo 'drone working'

#ssh connection to 161.35.247.162 woth secret private_key and root username
steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: 161.35.247.162
      port: 22
      username: root
      key:
        from_secret: private_key
      script:
        - echo 'drone working'
        - cd /home/ouadie/Game-backend
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_github
        - git pull
        - npm install
        - echo 'drone working 2'
