kind: pipeline
type: docker
name: default
 
steps:
  - name: log-message
    image: alpine
    commands:
      - echo "This 1 is a test log message from the Drone CI pipeline."
    when:
      event:
        - push

kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
- name: build
  image: docker:latest
  commands:
    - echo "Building the Docker image..."